# Generated by Django 4.1.3 on 2022-12-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_cheque',
            name='from_user',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
