# Generated by Django 4.1.3 on 2022-12-13 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0002_upload_cheque_from_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload_cheque',
            name='from_user',
        ),
    ]
